---
- name: Remove nginx default host config file
  file: 
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx

- name: Ensure nginx_vhost_path exists.
  file: 
    path: "{{  nginx_vhost_path  }}"
    state: directory
    mode: 0755
  notify: reload nginx

- name: Add main prod file into site-enable repo
  template: 
    src: production.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ project_name }}.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  notify: reload nginx 
  when: prod

- name: Add main dev file into site-enable repo
  template: 
    src: dev.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ project_name }}-dev.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  notify: reload nginx 
  when: dev

- name: Add main staging file into site-enable repo
  template: 
    src: staging.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ project_name }}-staging.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  notify: reload nginx 
  when: staging
