---
- name: creating dir for production doc-root
  file:
    path: "{{ nginx_doc_root_dev }}"
    state: directory
    recurse: yes
    owner: snapdev
    group: www-data
    mode: u=rwx,g=r,o=r
  when: prod == 'true'

- name: creating dir for dev doc-root
  file:
    path: "{{ nginx_doc_root_dev }}"
    state: directory
    recurse: yes
    owner: snapdev
    group: www-data
    mode: u=rwx,g=r,o=rwx
  when: dev == 'true'
    
- name: creating dir for staging doc-root
  file:
    path: "{{ nginx_doc_root_staging }}"
    state: directory
    recurse: yes
    owner: snapadmin   
    group: www-data
    mode: u=rwx,g=rwx,o=r
  when: staging == 'true'

- include: disable-apache2.yml
  static: yes
- include: install-nginx.yml
  static: yes
- include: mageHost.yml
  static: yes