---
- name: creating dir for production doc-root
  file:
    path: "{{ nginx_doc_root }}"
    state: directory
    recurse: yes
    owner: xdev
    group: www-data
    mode: u=rwx,g=rwx,o=rwx
  when: prod == 'true'

- name: creating dir for dev doc-root
  file:
    path: "{{ nginx_doc_root_dev }}"
    state: directory
    recurse: yes
    owner: xdev
    group: www-data
    mode: u=rwx,g=rwx,o=rwx
  when: dev == 'true'
    
- name: creating dir for staging doc-root
  file:
    path: "{{ nginx_doc_root_staging }}"
    state: directory
    recurse: yes
    owner: xadmin   
    group: www-data
    mode: u=rwx,g=rwx,o=rwx
  when: staging == 'true'

- include: disable-apache2.yml
  static: yes
- include_tasks: install-nginx.yml
#   when: prod == 'false'
# - include_tasks: nginx-pagespeed.yml
#   when: prod == 'true'
- include_tasks: nginx-config.yml
- include: mageHost.yml
  static: yes
