---
- name: Install common package
  apt: 
    name: "{{ common_packages }}"
    state: present
  with_items: "{{ common_packages }}"
- name: Set a hostname
  hostname:
    name: "{{ project_name }}"
- include_tasks: users.yml
