---
- name: Install common package
  apt: 
    name: "{{ common_packages }}"
    state: present
  with_items: "{{ common_packages }}"

# - include: os.yml  moving to optimize
#   static: no
- include_tasks: users.yml