---
- name: Add user , shell & homedir
  user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    createhome: "{{ item.home }}"
    # group: "{{ item.group }}"
  with_items: "{{ users }}"

- name: correct permission .ssh dir for each users
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name}}"
    group: "{{ item.name}}"
    mode: 0700
  with_items: "{{ users }}"

- name: Add the keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '{{ item.name }}') }}"
  with_items: "{{ users }}" 

- name: Sudo permission for added users role admin
  lineinfile:
    dest: "/etc/sudoers"
    insertafter: EOF
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    state: present
  when: item.use_sudo
  with_items: '{{ users }}'

  