---
sudo: required
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install tox-travis
script:
  - tox
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
