---
# handlers file for role_jenkins_slave
- name: Start Jenkins JNLP slave
  become: "yes"
  systemd:
    name: jenkins-slave
    enabled: "yes"
    state: restarted
    daemon_reload: "yes"
  when:  # Run this handler only if skip_start_service has been set to true
    - not (skip_start_service | default(true))
