---
# - include_role:
#     name: common
- name: include varfile
  include_vars:
    dir: vars
    files_matching: common.yml

- name: check java installed or not
  shell: which java 
  register: is_installed
  ignore_errors: yes

- name: Ensure Java is installed.
  apt:
    name: default-jre
    state: present
  when: is_installed.rc == 1

- name: add user group 
  include_role:
    name: common
    tasks_from: users.yml
  # vars_from:
  #   - include varfile
