---
- name: find all acpu config files 
  find:
    paths: "{{ item }}"
    contains: 'extension(\s+)?=(\s+)?apc[u]?\.so'
  register: php_installed_apc_confs
  with_items: "{{ php_extension_conf_paths }}"

- debug:
    msg: "00000000000000000 {{ item.item }} 00000000000000000"
  with_items: '{{ php_installed_apc_confs.results }}'

- name: remove non ansible-management acpu config file
  file:
    path: "{{ item.1.path }}"
    state: absent
  when: php_apc_conf_filename != (item.1.path.split('/') | last)
  with_subelements:
    - "{{ php_installed_apc_confs.results }}"
    - files
  notify: restart webserver

- name: config acpu config file
  template:
    src: apcu.ini.j2
    dest: "{{ item }}/{{ php_apc_conf_filename }}"
    owner: root
    group: root
    force: yes
    mode: 0644
  with_items: "{{ php_extension_conf_paths }}"
  when: php_enable_apc
  notify: restart webserver

- name: Remove APCu config file if APC is disabled.
  file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: not php_enable_apc
  notify: restart webserver
