---
- include: install_php_packages.yml
  static: no
  static: no
- include: configure.yml
  static: no
- include: configure-apcu.yml
  static: no
- include: composer.yml
  static: no
# - include: configure-fpm.yml
#   static: no