---
- include: install_php_packages.yml
  static: no
- include: configure.yml
  static: no
- include: configure-apcu.yml
  static: no
- include: memcached.yml
  when: memcached 
  static: no
- include: composer.yml
  static: no
- include: configure-fpm.yml
  static: no
# - include: configure-fpm-dev-staging.yml
#   static: no
#   when: dev 