---
- include: install_php_packages.yml
- include: configure.yml
- include: configure-apcu.yml
- include: memcached.yml # deprecated
  when: memcached        # deprecated : already set value false as default
- include: composer.yml
- include: configure-fpm.yml
