---
- name : config kernel
  command: "sysctl -w {{ item }}"
  with_items:
    - vm.max_map_count=262144
    - net.core.somaxconn=2048
    - net.core.netdev_max_backlog=5000    ### default is 1000 
  when: os_magento

